# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 1

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 1

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: []

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - help-wanted

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: true

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  ðŸ‘‹ Thanks for your contribution! ðŸ™Œ
   
  This issue has been automatically marked as `stale` because it has not had
  recent activity ðŸ’¤. Because the Electron App team treats their issues
  [as their backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog),
  stale issues will be closed after a week from the day of marking. If you
  would like this issue to remain open:
   
   1. Verify that you can still reproduce the issue in the latest version of Electron App
   2. Update the issue template with the following details:
      * What version of Electron App you reproduced the issue on
      * What OS and version you reproduced the issue on
      * What steps you followed to reproduce the issue
   3. Comment that the issue is still reproducible
   
  ðŸ™ Thank you for using Electron App! ðŸ™

# Comment to post when removing the stale label.
# unmarkComment: >
#   Your comment here.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  ðŸ‘‹ Thanks for your contribution! ðŸ™Œ
   
  This issue is being closed due to inactivity ðŸ’¤. If this is still an issue with
  the latest version of Electron App, please create a [new issue](https://github.com/hyperweavers/release-automation-sample-2/issues/new)
  and ensure the template is fully filled out.
   
  ðŸ™ Thank you for using Electron App! ðŸ™

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues` or `pulls`
only: issues

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
# pulls:
#   daysUntilStale: 30
#   markComment: >
#     This pull request has been automatically marked as stale because it has not had
#     recent activity. It will be closed if no further activity occurs. Thank you
#     for your contributions.

# issues:
#   exemptLabels:
#     - confirmed
